# coverage-badge.yml

name: Create coverage badge

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Java 17 needed for resolving the Android Gradle Plugin
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Cache Kotlin Native compiler
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: kotlin-native-compiler-${{ runner.OS }}

      - name: Generate coverage output
        # NOTE: the Android plugin is chatty with its output and spams stuff like "Install Android SDK ..."
        # This will mess up the next command (gradlew -q printLineCoverage) so we filter out anything that doesn't match
        # a very simple numeric value.
        run: |
          COVERAGE=$(${{github.workspace}}/gradlew -q printLineCoverage | grep -E '^[0-9]+(\.[0-9]+)?$')
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV

      - name: Update dynamic badge gist
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{secrets.COVERAGE_GIST_SECRET}}
          gistID: 01b6bfe88483946d9f5438f5616d9b9f
          filename: truthish-coverage-badge.json
          label: coverage
          message: ${{env.COVERAGE}}%
          valColorRange: ${{env.COVERAGE}}
          minColorRange: 0
          maxColorRange: 100
